const IO_EMIT = "IO_EMIT";
const SOCKET_BROADCAST = "SOCKET_BROADCAST";
const SOCKET_EMIT = "SOCKET_EMIT";
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const DEFAULT_BELOW_ALERT_THRESHOLD = 30;
const DEFAULT_ABOVE_ALERT_THRESHOLD = 500;

module.exports = {
    IO_EMIT: IO_EMIT,
    SOCKET_BROADCAST: SOCKET_BROADCAST,
    SOCKET_EMIT: SOCKET_EMIT,
    INCREMENT: INCREMENT,
    DECREMENT: DECREMENT,
    BELOW_ALERT_THRESHOLD: DEFAULT_BELOW_ALERT_THRESHOLD,
    ABOVE_ALERT_THRESHOLD: DEFAULT_ABOVE_ALERT_THRESHOLD
};